version: "3.8"

services:
  jupyter:
    image: jupyter/pyspark-notebook:x86_64-spark-3.5.0
    environment:
      - PYSPARK_SUBMIT_ARGS=--master spark://spark-master:7077 pyspark-shell
      - JUPYTER_TOKEN=miclustertoken
    ports:
      - "8888:8888"
    networks:
      - spark-net
    depends_on:
      - spark-master
    volumes:
      - datos_jupyter:/data
      - datos_jupyter:/home/jovyan/work

  spark-master:
    image: bitnami/spark:3.5.0-debian-12-r18
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-net
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
          - node.hostname == miguel
    volumes:
      - datos_jupyter:/data
      - datos_jupyter:/home/jovyan/work


  spark-worker-low:
    image: bitnami/spark:3.5.0-debian-12-r18
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    networks:
      - spark-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.tipo == low
    volumes:
      - datos_jupyter:/data
      - datos_jupyter:/home/jovyan/work


  spark-worker-medium:
    image: bitnami/spark:3.5.0-debian-12-r18
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    networks:
      - spark-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.tipo == medium

    volumes:
      - datos_jupyter:/data
      - datos_jupyter:/home/jovyan/work

  spark-worker-high:
    image: bitnami/spark:3.5.0-debian-12-r18
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
    networks:
      - spark-net
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.tipo == high
    volumes:
      - datos_jupyter:/data
      - datos_jupyter:/home/jovyan/work

networks:
  spark-net:
    driver: overlay

volumes:
  datos_jupyter:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.1,nolock,soft,rw"
      device: ":/srv/nfs/datos_jupyter"

